# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jekyll-simple" # the subpath of your site, e.g. /blog
url: "http://wildflame.me" # the base hostname & protocol for your site
twitter_username: Taffyer 
github_username:  wild-flame 

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

# prose.io front matter settings

prose:
  rooturl: '_posts'
  media: 'images'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Enter your title"
          value: ""
      - name: "layout"
        field:
          element: "hidden"
          value: "article"
      - name: "author"
        field:
          element: "hidden"
          value: "group5"
      - name: "group_members"
        field:
          element: "text"
          label: "Group members"
          value: ""
      - name: "modified"
        field:
          element: "hidden"
          value: CURRENT_DATETIME
      - name: "image_teaser"
        field:
          element: "hidden"
          value: ""
      - name: "storymap_id"
        field:
          element: "text"
          label: "Storymap ID"
          placeholder: "example: 772f6677de9353fe75919801ec1cb48b"
          help: "If including a Storymap, enter the string of characters included in your Storymap project URL"
          value: ""
      - name: "storymap_title"
        field:
          element: "text"
          label: "Storymap title"
          placeholder: "example: zombies-and-the-spread-of-fear"
          help: "If including a Storymap, enter the title associated with your Storymap project"
          value: ""
      - name: "timeline_id"
        field:
          element: "text"
          label: "Timeline ID"
          placeholder: "example: 1uGjhA8mK551YwHW1wRF5sh1utOxDV73JfuJbILe2jOI"
          help: "If including a Timeline, enter the string of characters included in your Timelinejs project URL"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish?"
          help: "Check the box when ready to publish"
          value: false
